# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GMail_MUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GMail_MUI

  pod 'mailcore2-ios'

  target 'GMail_MUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
